vpc_name                  = "java-vpc"
vpc_cidr_block            = "10.0.0.0/16"
environment               = "Production"
public_subnet_name        = "java-public-subnet"
public_subnet_cidr_block  = "10.0.1.0/24"
private_subnet_name       = "java-private-subnet"
private_subnet_cidr_block = "10.0.2.0/24"
internet_gateway_name     = "java-vpc-igw"